Repository operate-first/workshop-apps, pull requests merged in 2021-08, with the labels that each got.

#33 feat: Prepare for devconf US
  .pre-commit-config.yaml
  .prow.yaml
  README.md
  apps/devconf-us-2021.yaml
  apps/kustomization.yaml
  ml-prague-2021/create_app.sh
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/template-application.yaml
  ml-prague-2021/user1.yaml
  ml-prague-2021/user17.yaml
  ml-prague-2021/user28.yaml
  ml-prague-2021/user3.yaml
  ml-prague-2021/user7.yaml
  ml-prague-2021/user8.yaml
  policy/applicationset.rego
  policy/applicationset_test.rego
  policy/argocd_app.rego
Labels: size/L, approved, lgtm

#34 Update template issue
  .github/ISSUE_TEMPLATE/dev_conf_us_workshop.md
Labels: size/XS

#36 Add pacospace deployment
  apps/devconf-us-2021.yaml
Labels: size/XS, approved
