Repository operate-first/workshop-apps, pull requests merged in 2021-09, with the labels that each got.

#44 feat:add pacospace app
  apps/devconf-us-2021/pacospace.yaml
Labels: size/S, approved, lgtm

#47 feat: Enable cascade delete on app deletion
  apps/devconf-us-2021/mimotej.yaml
  apps/devconf-us-2021/pacospace.yaml
  apps/devconf-us-2021/tumido.yaml
  devconf-us-2021.sh
Labels: size/XS, approved, lgtm

#48 Delete apps
  apps/devconf-us-2021/mimotej.yaml
  apps/devconf-us-2021/pacospace.yaml
  apps/devconf-us-2021/tumido.yaml
Labels: size/M

#50 create pacospace app
  apps/devconf-us-2021/pacospace.yaml
Labels: size/S, approved, lgtm

#52 create diego-uchoa yaml
  apps/devconf-us-2021/diego-uchoa.yaml
Labels: size/S, approved, lgtm, ok-to-test

#53 Remove devconf apps.
  apps/devconf-us-2021/.keep
  apps/devconf-us-2021/codificat.yaml
  apps/devconf-us-2021/diego-uchoa.yaml
  apps/devconf-us-2021/pacospace.yaml
  apps/devconf-us-2021/tumido.yaml
Labels: size/M
