Repository operate-first/workshop-apps, pull requests merged in 2021-02, with the labels that each got.

#1 feat: Add basic setup for ML Prague 2021
  .github/workflows/conftest.yaml
  OWNERS
  README.md
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/template-application.yaml
  policy/argocd_app.rego
Labels: size/L

#2 chore: Add aicoe-ci conf and pre-commit
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  ml-prague-2021/kustomization.yaml
  policy/argocd_app.rego
Labels: size/M

#5 Introduce GitHub issue template for ML Prague workshop
  .github/ISSUE_TEMPLATE/ml_prague_workshop.md
Labels: approved, lgtm, size/S

#6 Make name issue specific for workshop
  .github/ISSUE_TEMPLATE/ml_prague_workshop.md
Labels: approved, lgtm, size/XS

#7 add test scripts for kustomize and conftest
  test-conftest
  test-kustomize-build
Labels: approved, lgtm, size/S

#10 Add a create_app script for the workshop and update policies for RHPDS
  README.md
  ml-prague-2021/create_app.sh
  ml-prague-2021/template-application.yaml
  policy/argocd_app.rego
Labels: size/M

#11 feat: Try out a test app
  .pre-commit-config.yaml
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/user55.yaml
Labels: size/S

#13 chore: Cleanup the test app
  .github/workflows/conftest.yaml
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/user55.yaml
Labels: size/S

#8 Use comma separated for assignees in issue template
  .github/ISSUE_TEMPLATE/ml_prague_workshop.md
Labels: approved, size/XS

#15 fix: Make the create_app script usable without kustomize binary
  ml-prague-2021/create_app.sh
Labels: approved, size/XS

#16 Deploy user1 application
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/user1.yaml
Labels: approved, size/S

#17 fix: MLPrague app manifest path
  ml-prague-2021/create_app.sh
  ml-prague-2021/user1.yaml
Labels: approved, lgtm, size/XS

#18 Deploy user17 app
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/user17.yaml
Labels: approved, needs-ok-to-test, size/S

#21 Add user28
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/user28.yaml
Labels: approved, needs-ok-to-test, size/S

#19 deploy
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/user8.yaml
Labels: approved, do-not-merge/hold, needs-ok-to-test, size/S

#23 fix: spacing
  ml-prague-2021/kustomization.yaml
Labels: approved, size/XS

#20 Add user3
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/user3.yaml
Labels: approved, size/S

#22 Register user7
  ml-prague-2021/kustomization.yaml
  ml-prague-2021/user7.yaml
Labels: approved, needs-ok-to-test, size/S
